# Startup

- repo: rafi/awesome-vim-colorschemes

- repo: christoomey/vim-tmux-navigator

- repo: yianwillis/vimcdoc

# Improve CursorHold performance
# See: https://github.com/neovim/neovim/issues/12587
- { repo: antoinemadec/FixCursorHold.nvim }

# Languages

- repo: sheerun/vim-polyglot

- repo: hail2u/vim-css3-syntax

- repo: othree/csscomplete.vim

- repo: groenewege/vim-less

- {
    repo: heavenshell/vim-jsdoc,
    'for': ['javascript', 'javascript.jsx', 'typescript', 'typescriptreact'],
    'do': 'make install',
  }

- repo: moll/vim-node

- {
    repo: dsznajder/vscode-es7-javascript-react-snippets,
    'do': 'yarn install --frozen-lockfile && yarn compile',
  }

- repo: alvan/vim-closetag

# Commands

# 🚀
- { repo: APZelos/blamer.nvim, 'on': ['BlamerToggle'] }

- repo: liuchengxu/vista.vim

- { repo: junegunn/fzf }

- { repo: junegunn/fzf.vim }

- repo: t9md/vim-choosewin

# 🚀
- { repo: kdheepak/lazygit.nvim, 'branch': 'nvim-v0.4.3', 'on': ['LazyGit'] }

- { repo: voldikss/vim-floaterm, 'on': ['FloatermNew'] }

- { repo: ianding1/leetcode.vim, 'on': ['LeetCodeList'] }

# Markdown

- repo: plasticboy/vim-markdown

- repo: iamcco/markdown-preview.nvim

# Editor UI

- repo: ryanoasis/vim-devicons

- repo: vim-airline/vim-airline

- repo: vim-airline/vim-airline-themes

# Interface

- repo: Konfekt/FastFold

- repo: easymotion/vim-easymotion

- repo: tpope/vim-surround

- repo: simeji/winresizer

- repo: rhysd/accelerated-jk

- repo: jiangmiao/auto-pairs

- repo: farmergreg/vim-lastplace

- repo: mg979/vim-visual-multi

- repo: preservim/nerdcommenter

# 🚀
- { repo: vim-scripts/BufOnly.vim, 'on': 'BufOnly' }

# 🚀
- repo: romainl/vim-cool

- repo: mhinz/vim-startify

# Completion and code analysis

- repo: neoclide/coc.nvim

- repo: antoinemadec/coc-fzf

- repo: honza/vim-snippets

# Git

- repo: airblade/vim-gitgutter
#  vim: set ts=2 sw=2 tw=80 et :
