---
# PLUGINS
# ===
# See config/plugins/all.vim for plugin mappings and config/plugins/*.vim

# Startup

- { repo: rafi/awesome-vim-colorschemes, merged: 0 }
- repo: christoomey/vim-tmux-navigator
  if: "! (has('win32') || has('win64'))"
- repo: yianwillis/vimcdoc

# Vim8 only:

- { repo: roxma/nvim-yarp, if: "! has('nvim')", depends: vim-hug-neovim-rpc }
- { repo: roxma/vim-hug-neovim-rpc, if: "! has('nvim')" }

# Languages

- repo: sheerun/vim-polyglot

- { repo: heavenshell/vim-jsdoc, on_ft: [ javascript, javascriptreact, typescript, typescriptreact ] }

- repo: dsznajder/vscode-es7-javascript-react-snippets
  build: 'yarn install --frozen-lockfile && yarn compile'

# Commands

- repo: liuchengxu/vista.vim
  on_cmd: Vista
  hook_add: |-
    let g:vista#renderer#enable_icon = 1
    let g:vista_echo_cursor_strategy = 'scroll'
    let g:vista_vimwiki_executive = 'markdown'
    let g:vista_executive_for = {
      \ 'vimwiki': 'markdown',
      \ 'pandoc': 'markdown',
      \ 'markdown': 'toc',
      \ }

- repo: junegunn/fzf
  merged: 0
  on_cmd: FZF
  type__depth: 1
  hook_source: |-
    let g:fzf_layout = { 'down': '~25%' }

- repo: junegunn/fzf.vim
  depends: fzf
  merged: 0
  on_cmd: [ Files, GitFiles, Buffers, Lines, Locate, Colors, Ag, Rg, Tags ]
  on_func: [ fzf#vim#with_preview, fzf#run, vista#finder#fzf#Run ]

- repo: wsdjeg/dein-ui.vim

- repo: Shougo/defx.nvim
  on_cmd: Defx
  hook_source: source $VIM_PATH/config/plugins/defx.vim

- { repo: kristijanhusak/defx-git, on_source: defx.nvim }

- { repo: kristijanhusak/defx-icons, on_source: defx.nvim }

- repo: t9md/vim-choosewin
  on_map: { n: <Plug> }
  hook_add: |-
    let g:choosewin_label = 'ADFGHJKLUIOPQWERT'
    let g:choosewin_label_padding = 5

- repo: kdheepak/lazygit.nvim
  on_cmd: LazyGit
  rev: nvim-v0.4.3

- repo: voldikss/vim-floaterm
  on_cmd: [FloatermNew, FloatermToggle, FloatermNext, FloatermPrev]
  hook_add: |-
    let g:floaterm_keymap_new    = '<F7>'
    let g:floaterm_keymap_prev   = '<F8>'
    let g:floaterm_keymap_next   = '<F9>'
    let g:floaterm_keymap_toggle = '<F12>'

- repo: liuchengxu/vim-clap
  build: ':Clap install-binary!'

# Denite

- repo: Shougo/denite.nvim
  on_cmd: Denite
  trusted: 1
  hook_source: source $VIM_PATH/config/plugins/denite.vim

# Markdown 

- repo: plasticboy/vim-markdown
  on_ft: markdown
  hook_add: |-
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_strikethrough = 1
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_conceal = 1
    let g:vim_markdown_conceal_code_blocks = 1
    let g:vim_markdown_new_list_item_indent = 0
    let g:vim_markdown_toc_autofit = 0
    let g:vim_markdown_edit_url_in = 'vsplit'
    let g:vim_markdown_fenced_languages = [
      \ 'c++=cpp',
      \ 'viml=vim',
      \ 'bash=sh',
      \ 'ini=dosini',
      \ 'js=javascript',
      \ 'json=javascript',
      \ 'jsx=javascriptreact',
      \ 'tsx=typescriptreact',
      \ 'docker=Dockerfile',
      \ 'makefile=make',
      \ 'py=python'
      \ ]

- repo: iamcco/markdown-preview.nvim
  on_ft: [markdown, pandoc.markdown, rmd]
  build: 'sh -c "cd app & yarn install"'

# Editor UI

- repo: ryanoasis/vim-devicons

- repo: glepnir/spaceline.vim

- repo: bagrat/vim-buffet

# Interface

- repo: easymotion/vim-easymotion
  on_map: { n: <Plug> }

- repo: tpope/vim-surround
  on_map: { n: <Plug> }

- repo: simeji/winresizer

- { repo: rhysd/accelerated-jk, on_map: { n: <Plug> }, if: $SUDO_USER == '' }

- repo: jiangmiao/auto-pairs
  on_map: { x: <Plug> }

- repo: luochen1990/rainbow
  hook_add: |-
    let g:rainbow_active = 1 

- repo: farmergreg/vim-lastplace

- repo: mg979/vim-visual-multi
  rev: 'master'

- repo: preservim/nerdcommenter
  hook_add: |-
    let g:NERDSpaceDelims = 1

- repo: vim-scripts/BufOnly.vim

- { repo: romainl/vim-cool, on_event: [ CursorMoved, InsertEnter ]}

- repo: glepnir/dashboard-nvim
  hook_add: source  $VIM_PATH/config/plugins/dashboard.vim

# Completion and code analysis

- repo: neoclide/coc.nvim
  merged: 0
  rev: 'release'
  hook_add: source  $VIM_PATH/config/plugins/coc.vim
  hook_source: source $VIM_PATH/config/plugins/lsp.vim

- repo: honza/vim-snippets
  depends : coc.nvim
  if: has('python3')
  merged: 0

#  vim: set ts=2 sw=2 tw=80 et :
